In [2]:
import pandas as pd
import os

In [ ]:
RAW_PATH = "../data/raw/abs/"

# G01 - Basic Demographics
g01 = pd.read_csv(os.path.join(RAW_PATH, "2021Census_G01_AUST_SA2.csv"))
# print('g01:', g01.columns.tolist())
g01 = g01[['SA2_CODE_2021', 'Tot_P_P', 'Age_20_24_yr_P', 'Age_25_34_yr_P']]
g01['pct_youth_18_34'] = (g01['Age_20_24_yr_P'] + g01['Age_25_34_yr_P']) / g01['Tot_P_P']
g01 = g01[['SA2_CODE_2021', 'Tot_P_P', 'pct_youth_18_34']]
g01.columns = ['sa2_code', 'total_pop', 'pct_youth_18_34']

g02 = pd.read_csv(os.path.join(RAW_PATH, "2021Census_G02_AUST_SA2.csv"))
print('g02:', g02.columns.tolist())
g02 = g02[['SA2_CODE_2021', 'Median_age_persons', 'Median_tot_prsnl_inc_weekly', 'Median_rent_weekly']]
g02.columns = ['sa2_code', 'median_age', 'median_weekly_income', 'median_weekly_rent']
# print('g02:', g02.columns.tolist())

g15 = pd.read_csv(os.path.join(RAW_PATH, "2021Census_G15_AUST_SA2.csv"))
g15 = g15[['SA2_CODE_2021', 'Tert_Tot_Tert_P', 'Tot_P']]
g15['pct_students'] =g15['Tert_Tot_Tert_P'] / g15['Tot_P']
g15 = g15[['SA2_CODE_2021', 'pct_students']]
g15.columns = ['sa2_code', 'pct_students']

df = g01 \
    .merge(g02, on='sa2_code', how='left') \
    .merge(g15, on='sa2_code', how='left')

df['rent_to_income_ratio'] = df['median_weekly_rent'] / df['median_weekly_income']
df = df.dropna()
df.to_csv("../data/processed/abs_demographics_merged.csv", index=False)
df

g01: ['SA2_CODE_2021', 'Tot_P_M', 'Tot_P_F', 'Tot_P_P', 'Age_0_4_yr_M', 'Age_0_4_yr_F', 'Age_0_4_yr_P', 'Age_5_14_yr_M', 'Age_5_14_yr_F', 'Age_5_14_yr_P', 'Age_15_19_yr_M', 'Age_15_19_yr_F', 'Age_15_19_yr_P', 'Age_20_24_yr_M', 'Age_20_24_yr_F', 'Age_20_24_yr_P', 'Age_25_34_yr_M', 'Age_25_34_yr_F', 'Age_25_34_yr_P', 'Age_35_44_yr_M', 'Age_35_44_yr_F', 'Age_35_44_yr_P', 'Age_45_54_yr_M', 'Age_45_54_yr_F', 'Age_45_54_yr_P', 'Age_55_64_yr_M', 'Age_55_64_yr_F', 'Age_55_64_yr_P', 'Age_65_74_yr_M', 'Age_65_74_yr_F', 'Age_65_74_yr_P', 'Age_75_84_yr_M', 'Age_75_84_yr_F', 'Age_75_84_yr_P', 'Age_85ov_M', 'Age_85ov_F', 'Age_85ov_P', 'Counted_Census_Night_home_M', 'Counted_Census_Night_home_F', 'Counted_Census_Night_home_P', 'Count_Census_Nt_Ewhere_Aust_M', 'Count_Census_Nt_Ewhere_Aust_F', 'Count_Census_Nt_Ewhere_Aust_P', 'Indigenous_psns_Aboriginal_M', 'Indigenous_psns_Aboriginal_F', 'Indigenous_psns_Aboriginal_P', 'Indig_psns_Torres_Strait_Is_M', 'Indig_psns_Torres_Strait_Is_F', 'Indig_psns_Torres_Strait_Is_P', 'Indig_Bth_Abor_Torres_St_Is_M', 'Indig_Bth_Abor_Torres_St_Is_F', 'Indig_Bth_Abor_Torres_St_Is_P', 'Indigenous_P_Tot_M', 'Indigenous_P_Tot_F', 'Indigenous_P_Tot_P', 'Birthplace_Australia_M', 'Birthplace_Australia_F', 'Birthplace_Australia_P', 'Birthplace_Elsewhere_M', 'Birthplace_Elsewhere_F', 'Birthplace_Elsewhere_P', 'Lang_used_home_Eng_only_M', 'Lang_used_home_Eng_only_F', 'Lang_used_home_Eng_only_P', 'Lang_used_home_Oth_Lang_M', 'Lang_used_home_Oth_Lang_F', 'Lang_used_home_Oth_Lang_P', 'Australian_citizen_M', 'Australian_citizen_F', 'Australian_citizen_P', 'Age_psns_att_educ_inst_0_4_M', 'Age_psns_att_educ_inst_0_4_F', 'Age_psns_att_educ_inst_0_4_P', 'Age_psns_att_educ_inst_5_14_M', 'Age_psns_att_educ_inst_5_14_F', 'Age_psns_att_educ_inst_5_14_P', 'Age_psns_att_edu_inst_15_19_M', 'Age_psns_att_edu_inst_15_19_F', 'Age_psns_att_edu_inst_15_19_P', 'Age_psns_att_edu_inst_20_24_M', 'Age_psns_att_edu_inst_20_24_F', 'Age_psns_att_edu_inst_20_24_P', 'Age_psns_att_edu_inst_25_ov_M', 'Age_psns_att_edu_inst_25_ov_F', 'Age_psns_att_edu_inst_25_ov_P', 'High_yr_schl_comp_Yr_12_eq_M', 'High_yr_schl_comp_Yr_12_eq_F', 'High_yr_schl_comp_Yr_12_eq_P', 'High_yr_schl_comp_Yr_11_eq_M', 'High_yr_schl_comp_Yr_11_eq_F', 'High_yr_schl_comp_Yr_11_eq_P', 'High_yr_schl_comp_Yr_10_eq_M', 'High_yr_schl_comp_Yr_10_eq_F', 'High_yr_schl_comp_Yr_10_eq_P', 'High_yr_schl_comp_Yr_9_eq_M', 'High_yr_schl_comp_Yr_9_eq_F', 'High_yr_schl_comp_Yr_9_eq_P', 'High_yr_schl_comp_Yr_8_belw_M', 'High_yr_schl_comp_Yr_8_belw_F', 'High_yr_schl_comp_Yr_8_belw_P', 'High_yr_schl_comp_D_n_g_sch_M', 'High_yr_schl_comp_D_n_g_sch_F', 'High_yr_schl_comp_D_n_g_sch_P', 'Count_psns_occ_priv_dwgs_M', 'Count_psns_occ_priv_dwgs_F', 'Count_psns_occ_priv_dwgs_P', 'Count_Persons_other_dwgs_M', 'Count_Persons_other_dwgs_F', 'Count_Persons_other_dwgs_P']
g01: ['sa2_code', 'total_pop', 'pct_youth_18_34']
g02: ['SA2_CODE_2021', 'Median_age_persons', 'Median_mortgage_repay_monthly', 'Median_tot_prsnl_inc_weekly', 'Median_rent_weekly', 'Median_tot_fam_inc_weekly', 'Average_num_psns_per_bedroom', 'Median_tot_hhd_inc_weekly', 'Average_household_size']

,sa2_code,total_pop,pct_youth_18_34,median_age,median_weekly_income,median_weekly_rent,pct_students,rent_to_income_ratio
0,101021007,4343,0.113055,51,760,330,0.154905,0.434211
1,101021008,8517,0.208994,38,975,350,0.207961,0.358974
2,101021009,11342,0.269529,37,996,330,0.297753,0.331325
3,101021010,5085,0.282399,36,1104,310,0.316605,0.280797
4,101021012,12744,0.174592,37,1357,430,0.241497,0.316875
...,...,...,...,...,...,...,...,...
2463,801111141,63,0.174603,27,1270,400,0.111111,0.314961
2466,901011001,1692,0.231678,38,1233,150,0.059379,0.121655
2467,901021002,593,0.170320,40,741,231,0.050251,0.311741
2468,901031003,310,0.170968,38,585,90,0.069930,0.153846
2469,901041004,2188,0.107404,50,736,240,0.109375,0.326087